(function() {var implementors = {};
implementors['libc'] = [];implementors['openssl'] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/convert/trait.AsRef.html' title='core::convert::AsRef'>AsRef</a>&lt;<a class='struct' href='https://doc.rust-lang.org/nightly/std/ffi/os_str/struct.OsStr.html' title='std::ffi::os_str::OsStr'>OsStr</a>&gt; for <a class='primitive' href='https://doc.rust-lang.org/nightly/std/primitive.str.html'>str</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/convert/trait.AsRef.html' title='core::convert::AsRef'>AsRef</a>&lt;<a class='struct' href='https://doc.rust-lang.org/nightly/std/path/struct.Path.html' title='std::path::Path'>Path</a>&gt; for <a class='primitive' href='https://doc.rust-lang.org/nightly/std/primitive.str.html'>str</a>",];implementors['kafka'] = ["impl&lt;'a&gt; <a class='trait' href='https://doc.rust-lang.org/nightly/core/convert/trait.AsRef.html' title='core::convert::AsRef'>AsRef</a>&lt;<a class='struct' href='kafka/client/struct.FetchGroupOffset.html' title='kafka::client::FetchGroupOffset'>FetchGroupOffset</a>&lt;'a&gt;&gt; for <a class='struct' href='kafka/client/struct.FetchGroupOffset.html' title='kafka::client::FetchGroupOffset'>FetchGroupOffset</a>&lt;'a&gt;","impl&lt;'a&gt; <a class='trait' href='https://doc.rust-lang.org/nightly/core/convert/trait.AsRef.html' title='core::convert::AsRef'>AsRef</a>&lt;<a class='struct' href='kafka/client/struct.CommitOffset.html' title='kafka::client::CommitOffset'>CommitOffset</a>&lt;'a&gt;&gt; for <a class='struct' href='kafka/client/struct.CommitOffset.html' title='kafka::client::CommitOffset'>CommitOffset</a>&lt;'a&gt;","impl&lt;'a, 'b&gt; <a class='trait' href='https://doc.rust-lang.org/nightly/core/convert/trait.AsRef.html' title='core::convert::AsRef'>AsRef</a>&lt;<a class='struct' href='kafka/client/struct.ProduceMessage.html' title='kafka::client::ProduceMessage'>ProduceMessage</a>&lt;'a, 'b&gt;&gt; for <a class='struct' href='kafka/client/struct.ProduceMessage.html' title='kafka::client::ProduceMessage'>ProduceMessage</a>&lt;'a, 'b&gt;","impl&lt;'a&gt; <a class='trait' href='https://doc.rust-lang.org/nightly/core/convert/trait.AsRef.html' title='core::convert::AsRef'>AsRef</a>&lt;<a class='struct' href='kafka/client/struct.FetchPartition.html' title='kafka::client::FetchPartition'>FetchPartition</a>&lt;'a&gt;&gt; for <a class='struct' href='kafka/client/struct.FetchPartition.html' title='kafka::client::FetchPartition'>FetchPartition</a>&lt;'a&gt;",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
